name: Publish to pub.dev

on:
  push:
  #  tags:
  #    - "v[0-9]+.[0-9]+.[0-9]+" # tag-pattern on pub.dev: 'v{{version}}'

# Publish using the reusable workflow from dart-lang.
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v4
      - name: ğŸ¦ Setup Flutter
        uses: subosito/flutter-action@v2

      - name: ğŸªª Get Id Token
        uses: actions/github-script@v6
        with:
          script: |
            let pub_token = await core.getIDToken('https://pub.dev')
            core.exportVariable('PUB_TOKEN', pub_token)

      - name: ğŸ“¢ Authenticate
        shell: ${{ inputs.shell }}
        run: flutter pub pub token add https://pub.dev --env-var PUB_TOKEN

      - name: ğŸ“¦ Install dependencies
        shell: ${{ inputs.shell }}
        run: flutter pub get
        working-directory: ${{ inputs.working-directory }}

      - name: ğŸŒµ Dry Run
        shell: ${{ inputs.shell }}
        run: flutter pub publish --dry-run
        working-directory: ${{ inputs.working-directory }}

      - name: ğŸ“¢ Publish
        shell: ${{ inputs.shell }}
        run: flutter pub publish -f
        working-directory: ${{ inputs.working-directory }}
